### ISSUE TITLE
Design for Homepage

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#144] opened 2015-03-31 16:06 UTC
Visual design for Principles> Introduction page.

Wireframe [here.](http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/axure%20wireframes/principles.html)

**Comment by poofichu** [comment] 2015-04-05 22:53
Relies on #121.  Moving to blocked until content is determined.

**Comment by poofichu** [comment] 2015-04-07 20:40
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

New content in, Josh approved and ready for review.

**Comment by kathrynmcelroy** [comment] 2015-04-08 16:23
:+1:

**Comment by una** [comment] 2015-04-08 16:25
I'd love to see that top logo animate in with @ryanbrownhill's animation :)

**Comment by britanyponvelle** [comment] 2015-04-08 16:25
The centered text on this page feels disconnected from the other pages (since we don't center text anywhere else). Also, I don't know if the bolded text in the titles adds value here. Since the text is set in an H tag, I think that could be enough distinction from the body text. Especially in "Meet Watson", because it almost looks like we are recreating the logo with the regular paired with bold Helvetica.

**Comment by bobbinrobyn** [comment] 2015-04-08 16:29
I agree with @britanyponvelle that the centered text is a tad weird. Maybe if there was a fill behind the logo and the "Meet Watson" line, it would feel more like a unified graphic and we could get away with centered text?

Otherwise, content looks good to me.

**Comment by una** [comment] 2015-04-08 16:30
I agree with @britanyponvelle about the centered text feeling disjointed (I'm looking at the grey box). Also, I would take a look at the copy used in that grey box for the links. It doesn't give much of an accurate descriptor into the content I am about to click into. What is the difference between the two links and how can we differentiate this? Both of them seem lead me to more information about Watson.

**Comment by britanyponvelle** [comment] 2015-04-08 16:32
I like the idea of a fill behind the first section (right before the H2). What if it was filled with the same color as the nav box?

**Comment by bobbinrobyn** [comment] 2015-04-08 16:34
To @una's point, it might be as simple as replacing "a deep dive" with "additional explanation about". The first link points to explanation, the second link points to actually using Watson.

**Comment by kathrynmcelroy** [comment] 2015-04-08 16:36
Agreed on the link description and centered text fixes.

**Comment by poofichu** [comment] 2015-04-13 19:45
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

New homepage coded.

**Comment by britanyponvelle** [comment] 2015-04-13 20:01
Great job @poofichu ! Thoughts from @channel about the `aside` box here? I feel like the likes belong in a `resources` box, since that is how we are treating external links on other pages.

**Comment by joshkimmell** [comment] 2015-04-13 20:09
@britanyponvelle: I disagree. This is an inline `aside` not a resource. It requires the text around it to give it context.

**Comment by britanyponvelle** [comment] 2015-04-13 20:21
@joshkimmell I hear you, that makes sense.
@poofichu The height for the hero image looks good for large screens, but the height on mobile feels a bit tight. (Also the Major Third is 2.441em for that text :) Forgot to send you that before)

**Comment by poofichu** [comment] 2015-04-13 20:51
Okay, text updated and hero spacing fixed.  Take a look again @britanyponvelle @joshkimmell ?

**Comment by bobbinrobyn** [comment] 2015-04-13 20:59
This is maybe just a weird prototype thing – the avatar image floats left with no padding on large screen sizes and floats right with some padding on smaller sizes.

**Comment by kathrynmcelroy** [comment] 2015-04-13 21:00
The break point for large to medium forces the main title into two lines before breaking (messing up the nav menu)

![screen shot 2015-04-13 at 4 00 04 pm](https://cloud.githubusercontent.com/assets/5400092/7125416/38211ece-e1f6-11e4-8537-d5388188ff65.png)

**Comment by poofichu** [comment] 2015-04-13 21:22
@bobbinrobyn that was intentional
@kathrynmcelroy that's a jQuery thing.  Good catch!  I'll see if I can get it to work, but if not we'll have to move on.

**Comment by britanyponvelle** [comment] 2015-04-13 21:34
This looks better! :+1:

**Comment by bobbinrobyn** [comment] 2015-04-14 15:56
Two things - 
1. I need to give you a new image for the 8th SVG on the page. I goofed up and forgot to take out one of the backgrounds.
2. The nav button on the bottom of the page needs to say something other than "Previous Page: Values"

**Comment by bobbinrobyn** [comment] 2015-04-14 16:00
... But it's going to be pretty hard to know what to call the previous page until Josh decides what to call the previous page. #whompwhomp

**Comment by bobbinrobyn** [comment] 2015-04-14 16:01
... But it's going to pretty hard to know what to call the previous page until Josh decides what to call the previous page. #whompwhomp

**Comment by joshkimmell** [comment] 2015-04-14 16:31
Official name: Introduction

**Comment by ryanbrownhill** [comment] 2015-04-16 15:03
The nav bar changes names from Principles to Introduction - FYI

![screen shot 2015-04-16 at 10 00 43 am](https://cloud.githubusercontent.com/assets/9538395/7183888/aad58c2c-e41f-11e4-9314-1e7d8ae734d0.png)
![screen shot 2015-04-16 at 10 00 47 am](https://cloud.githubusercontent.com/assets/9538395/7183887/aad42bde-e41f-11e4-86be-24d8954a73a8.png)

**Comment by ryanbrownhill** [comment] 2015-04-21 16:26
Main nav = Principles not Introduction @poofichu 
:+1: design done

**Comment by britanyponvelle** [comment] 2015-04-21 16:28
:+1:

**Comment by bobbinrobyn** [comment] 2015-04-21 17:16
:-1: I vote not done. Mainly because @joshkimmell just let me look over his shoulder, and I know he's still trying some different things out. But those issues might have all been broken out in #175, #176, and #177

**Comment by Snugug** [comment] 2015-05-02 14:19
Is this still relevant? Or has this now become a duplicate of #121 now that onboarding isn't part of principles?

**Comment by poofichu** [comment] 2015-05-04 15:27
I'm going to close this since yes, onoboarding isn't part of principles anymore.

**Closed** 2015-05-04 15:27 UTC
Labels: design library, ready for review, visual design
