### ISSUE TITLE
Refine Viewport on Mobile for UI Patterns Page

### ISSUE THREAD

**Issue by ryanbrownhill** [IBM-Watson/design-library#383] opened 2015-05-20 14:41 UTC
The viewport for the UI Patterns page renders differently then Principles & Guidlines

**Comment by ryanbrownhill** [comment] 2015-05-20 14:44
![img_5447](https://cloud.githubusercontent.com/assets/9538395/7728417/b89f65ba-fed4-11e4-9ba7-994d62315395.PNG)
![img_5446](https://cloud.githubusercontent.com/assets/9538395/7728416/b89ecd58-fed4-11e4-9176-03da2cf6cb06.PNG)

**Comment by Snugug** [comment] 2015-06-08 17:42
Duplicate of #390

**Closed by Snugug** 2015-06-08 17:42 UTC
Labels: bug, help wanted
