### ISSUE TITLE
Define URL Structure for site

### ISSUE THREAD

**Issue by kathrynmcelroy** [IBM-Watson/design-library#152] opened 2015-04-01 20:11 UTC
Define the URL structure and redirection guide

**Comment by kathrynmcelroy** [comment] 2015-04-07 16:38
/Principles --> goes to /Principles/GettingStarted
/Principles/GettingStarted
/Principles/DesignPrinciples

/Guidelines --> goes to /Guidelines/Style/Accessibility

/Guidelines/Style/ --> goes to /Guidelines/Style/Accessibility
/Guidelines/Style/Accessibility
/Guidelines/Style/Color
/Guidelines/Style/Iconography
/Guidelines/Style/Grids
/Guidelines/Style/Typography

/Guidelines/Interaction --> goes to /Guidelines/Interaction/Animation
/Guidelines/Interaction/Animation
/Guidelines/Interaction/SignaturePatterns
/Guidelines/Interaction/SignaturePatterns/Avatar


/Guidelines/Branding --> goes to /Guidelines/Branding/Wordmark
/Guidelines/Branding/Wordmark

**Comment by Snugug** [comment] 2015-04-16 19:51
Looking at the prototype for gauge on working IA:
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/design_principles.html

Some thoughts:
* Are Design Principles really a child of Introduction? If so, what's the URL structure there? `url.com/principles`? Everything here is linking to a direct HTML file, we're going to want clean URLs
* Navigating to `Guidelines` changes the nav from `Introduction` to `Principles`. Clicking `Principles` changes nav to `Introduction`. Seeing this in action, I'm not digging `Design Principles` being a "child" of `Introduction`, especially because of the large diff in page layout w/o the header (but that's not an IA issue)

Related to #93

**Comment by Snugug** [comment] 2015-04-16 20:02
Also, question about this. Does this mean that the home page redirects to `principles/getting-started`?

**Comment by kathrynmcelroy** [comment] 2015-04-16 21:27
- Design Principles are not a child of Introduction, they both are children of Principles
- We do not have a landing page, the base page of our website is the Introduction page
- The top-level menu should be "Principles" "Guidelines" "UI Patterns"; and the secondary nav within "Principles" should be "Introduction" and "Design Principles" which are both the same child-level within principles.

Updated URL Structures based on recent page title changes:
/Principles --> goes to /Principles/Introduction
/Principles/Introduction
/Principles/DesignPrinciples

/Guidelines --> goes to /Guidelines/Style/Accessibility

/Guidelines/Style/ --> goes to /Guidelines/Style/Accessibility
/Guidelines/Style/Accessibility
/Guidelines/Style/Color
/Guidelines/Style/Grids
/Guidelines/Style/Iconography
/Guidelines/Style/Typography

/Guidelines/Interaction --> goes to /Guidelines/Interaction/Animation
/Guidelines/Interaction/Animation
/Guidelines/Interaction/SignaturePatterns
/Guidelines/Interaction/SignaturePatterns/Avatar

/Guidelines/Branding --> goes to /Guidelines/Branding/BrandAttributes
/Guidelines/Branding/BrandAttributes
/Guidelines/Branding/Wordmark

**Comment by Snugug** [comment] 2015-04-16 21:54
Being immediately redirected upon getting to our home page is going to confuse a whole tonne of people. Like, that's just not how websites work confusion. I understand we added it there so that it had the sidebar, but personally I'm okay with not having a sidebar on the introduction page if it means this is the alternative. I think it'll wind up working, too, as the layout is so dissimilar there won't be confusion. Currently, going to from the Introduction page to the Principles page through sidebar navigation is very jarring because of the jump caused by the header.

**Comment by bobbinrobyn** [comment] 2015-04-17 19:37
@kathrynmcelroy and I discussed the redirecting issue. It's a tough one, with no immediately obvious solution. Here's the compromise we would like to suggest:

- Leave the Introduction page layout exactly the same, including the sidebar. (We think users need a very obvious way to get back to the Introduction information, beyond just clicking the logo in the header as a non-obvious "home" button.)
- Change the URL of the Introduction page to /index.html
- When you click over to Design Principles, the URL changes to /principles/design-principles.html

And if we find out in user testing that the jump caused by the header is jarring, then @ryanbrownhill says we can incorporate a short slide-up animation.

**Comment by Snugug** [comment] 2015-04-18 13:28
* Clicking a site's logo to go to a home page is one of the most prevalent patterns on the web and has been used for a very very long time. Wanting a more obvious way to get home is fine, but I'm not convinced that users wouldn't know that clicking the logo wouldn't take them home. In fact, I'd say that the default assumption by users would be to try that. If we don't have user testing saying otherwise, I'd use the pretty universally standard `logo home` pattern.
* Changing the URL is fine, but the top URL structure doesn't make much sense to me. Clicking "Principles" brings you to the home page? Or is the introduction a "Principle" too? Don't we think that it's weird that sub-nav instead is doing major site navigation, to `/principles/design-principles`, but none of the other top nav items can be navigated to in the same way?
* Intercepting a page change isn't particularly easy and raises a bunch of new questions, like what is that animation like? Does the header slide away then the content fades out and the new content fades in? Does it slide up then the page changes as normal?

**Comment by Snugug** [comment] 2015-04-18 15:27
WRG the site logo navigation, some further investigation:

* http://guidelines.usability.gov/
* http://guidelines.usability.gov/chapters/5/introduction
* http://guidelines.usability.gov/guidelines/46
* http://guidelines.usability.gov/guidelines/49
* http://guidelines.usability.gov/guidelines/51
* http://ux.stackexchange.com/questions/5003/home-button-vs-logo-link
* http://www.nngroup.com/articles/113-design-guidelines-homepage-usability/
* https://twitter.com/Snugug/status/589440593497083904 (Informal poll on Twitter)

It seems like general best practices are:
* Make sure the homepage of a site is distinct and easily recognizable as a stand-alone homepage.
* Link to the home page from both the logo and a distinct homepage link.

From this bit of research I have the following suggestions to make:

* Decouple the home page from the Principles. This includes removing it from the Principle's sidebar, removing its sidebar, removing the footer navigation to principles, and providing its own main navigation link
* Replace the Values section in Principles ([it exists, right?](http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/values.html)) to ensure there is a sidebar for Principles and Values (presuming it still exists). If not, consider exploding principles into individual principles into individual pages.

**Comment by bobbinrobyn** [comment] 2015-04-21 16:41
So @joshkimmell and @Snugug are deciding the URL before ".com".

As far as after the ".com", here is the updated URL structure:

**/Home?**

**/Principles --> goes to /Principles/IntroduceCognitive**
**/Principles/IntroduceCognitive**
**/Principles/InformInteractions**
**/Principles/OfferControl**

/Guidelines --> goes to /Guidelines/Style/Accessibility

/Guidelines/Style/ --> goes to /Guidelines/Style/Accessibility
/Guidelines/Style/Accessibility
/Guidelines/Style/Color
/Guidelines/Style/Grids
**~~/Guidelines/Style/Iconography~~**
/Guidelines/Style/Typography

/Guidelines/Interaction --> goes to /Guidelines/Interaction/Animation
/Guidelines/Interaction/Animation
/Guidelines/Interaction/SignaturePatterns
/Guidelines/Interaction/SignaturePatterns/Avatar

/Guidelines/Branding --> goes to /Guidelines/Branding/BrandAttributes
/Guidelines/Branding/BrandAttributes
/Guidelines/Branding/Wordmark

**Comment by ryanbrownhill** [comment] 2015-04-21 16:45
:+1: looks good to me shall we open an new issue for the ".com" issue?

**Comment by britanyponvelle** [comment] 2015-04-21 16:47
I still have concerns about the Brand Attributes content in #159 and #160 as I'm not sure what value we are adding/ if it can live alongside something more actionable

**Comment by bobbinrobyn** [comment] 2015-04-21 17:08
@ryanbrownhill: That's its own issue already (#161)

@britanyponvelle: I'll do some thinking today around the Brand Attributes and see if we can come up with a good solution. But agreed, let's not close this issue until that's decided.

**Comment by Snugug** [comment] 2015-04-23 15:21
@bobbinrobyn Is this resolved after our conversation yesterday?

**Comment by bobbinrobyn** [comment] 2015-04-23 15:51
/Home

/Principles --> goes to /Principles/IntroduceCognitive
/Principles/IntroduceCognitive
/Principles/InformInteractions
/Principles/OfferControl

/Guidelines --> goes to /Guidelines/Style/Accessibility

/Guidelines/Style/ --> goes to /Guidelines/Style/Accessibility
/Guidelines/Style/Accessibility
/Guidelines/Style/Color
/Guidelines/Style/Grids
/Guidelines/Style/Typography

/Guidelines/Interaction --> goes to /Guidelines/Interaction/Animation
/Guidelines/Interaction/Animation
/Guidelines/Interaction/SignaturePatterns
/Guidelines/Interaction/SignaturePatterns/Avatar

/Guidelines/Branding --> goes to /Guidelines/Branding/BrandAttributes
**/Guidelines/Branding/BrandAttributes**
/Guidelines/Branding/Wordmark

/UIPatterns --> Goes to /UIPatterns/Documentation/GettingStarted

/UIPatterns/Documentation --> goes to /UIPatterns/Documentation/GettingStarted
/UIPatterns/Documentation/GettingStarted
/UIPatterns/Documentation/Settings
/UIPatterns/Documentation/Animation
/UIPatterns/Documentation/JavascriptStandards

/UIPatterns/Patterns --> goes to /UIPatterns/Patterns/Elements
/UIPatterns/Patterns/Elements
+ /UIPatterns/Patterns/Elements/anchorlink
+ /UIPatterns/Patterns/Elements/blockquote
+ /UIPatterns/Patterns/Elements/body
+ /UIPatterns/Patterns/Elements/button
+ [...]
/UIPatterns/Patterns/Components
/UIPatterns/Patterns/Layouts

**Comment by bobbinrobyn** [comment] 2015-04-23 15:52
@Snugug As far as I know, only the bolded line is in question (brand attributes). But I updated the bottom of the list with the results of our convo.

**Comment by bobbinrobyn** [comment] 2015-04-23 21:43
Okay, here's the updated URL structure. Ready to close! :+1: 

/Home

/Principles --> goes to /Principles/IntroduceCognitive
/Principles/IntroduceCognitive
/Principles/InformInteractions
/Principles/OfferControl

/Guidelines --> goes to /Guidelines/Style/Accessibility

/Guidelines/Style/ --> goes to /Guidelines/Style/Accessibility
/Guidelines/Style/Accessibility
/Guidelines/Style/Color
/Guidelines/Style/Grids
/Guidelines/Style/Typography

/Guidelines/Interaction --> goes to /Guidelines/Interaction/Animation
/Guidelines/Interaction/Animation
/Guidelines/Interaction/SignaturePatterns
/Guidelines/Interaction/SignaturePatterns/Avatar

/Guidelines/Branding --> goes to /Guidelines/Branding/Wordmark
/Guidelines/Branding/Wordmark

/UIPatterns --> Goes to /UIPatterns/Documentation/GettingStarted

/UIPatterns/Documentation --> goes to /UIPatterns/Documentation/GettingStarted
/UIPatterns/Documentation/GettingStarted
/UIPatterns/Documentation/Settings
/UIPatterns/Documentation/Animation
/UIPatterns/Documentation/JavascriptStandards

/UIPatterns/Patterns --> goes to /UIPatterns/Patterns/Elements
/UIPatterns/Patterns/Elements
+ /UIPatterns/Patterns/Elements/anchorlink
+ /UIPatterns/Patterns/Elements/blockquote
+ /UIPatterns/Patterns/Elements/body
+ /UIPatterns/Patterns/Elements/button
+ [...]

/UIPatterns/Patterns/Components
/UIPatterns/Patterns/Layouts

**Comment by britanyponvelle** [comment] 2015-04-23 21:44
:+1:

**Comment by ryanbrownhill** [comment] 2015-04-23 21:45
:+1:  closed via final structure in the comment above.

**Closed by ryanbrownhill** 2015-04-23 21:45 UTC
